### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Samuell1** [spirit/spirit#1]
any simple tutorial how to install and use it?

**Comment by inlet** [comment]
Hi Samuel,

This lib can eventually be used in conjunction with Spirit app, which is currently in beta development. 
So right now you won't be able to use this piece of code. Make sure you signup at https://spiritjs.io to keep track on updates!

Thanks!

Cheers, Patrick

**Comment by Samuell1** [comment]
Thanks for fast reply! I waiting for this cool app!

**Comment by thierryc** [comment]
Me too ! I waiting for this cool app!
