### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by rmros** [spirit/spirit#10]
Thank you create this valuable thing
I cant find any demo and i dont know how use it
Where is api document?
Give me some demo
😁

**Comment by inlet** [comment]
Hi @rmros, thanks! I am working hard to get the beta shipped asap. Sign up at [https://spiritapp.io](https://spiritapp.io) and I keep you posted on any progress. 

Please email me if you have further questions. Let's use issues for code related issues only, thanks in advance!

Best regards,
Patrick

**Comment by rmros** [comment]
mr @inlet i have some quastations, please check your email now
