### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by peteringram0** [spirit/spirit#11]
I have a license for the beta preview. The install says 'Click on the browser extension to connect' however its unclear where that is?

**Comment by inlet** [comment]
Hi Peter,

Thanks for your feedback. 

Could you please send me future feedback to support@spiritapp.io and keep these issues for code related things only, thanks in advance!

It would be very helpful if you could send extra info (screenshots/description/etc.), this could help me to better understand what you're experiencing and how to best troubleshoot the issue.

Thanks

Kind regards, Patrick
