### ISSUE TITLE
About reuse GSAP

### ISSUE THREAD

**Issue by GoreStarry** [spirit/spirit#12]
Hi @inlet, thx to create this awesome timeline dev tool.
And I want to ask about, Is it possible to get global GSAP like TweenMax and TimelineMax from spriit.js? 
I have noticed the timeline animation tool like bodymovin which the plugin export the animation JSON for After Effect. 
And the biggest problem of that is the lib can only to play the animation JSON data, it's meaning to if I want to make the animation otherwhere, I must include the other animation lib cause the web size wasted.
Since spirit use the GSAP at the beginning, can I use the GSAP by only include the spirit.js?

**Comment by inlet** [comment]
Hi Gore, 

Please use this issue section for code related things only. If you've questions about the tool or something else, I'd be glad to answer them for you via mail at [support@spiritapp.io](mailto:support@spiritapp.io)

Don't quite follow you, please explain you question more clearly. Let's continue the conversation by mail. Thanks in advance!

Patrick
