### ISSUE TITLE
Root not being saved

### ISSUE THREAD

**Issue by Tam** [spirit/spirit#15]
This is specifically an app issue rather than the runtime, but I'm not sure where else to submit it!

**Spirit version:** v0.11.12-beta

**Steps to reproduce:**
1. Create a group and set the root to be something other than body.
2. Save the JSON, then reload the page & re-open in Spirit.

**Expected behavior:**
The root should be saved along with the group.

**Actual behavior:**
The root isn't saved to the JSON which causes an `Unable to resolve element by path expression` when the Spirit runtime loads the JSON.

**Additional information:**
Setting the root is useful, but would it be possible to not need an absolute XPath? Being able to do something like `//*[@data-spirit-id='myElement']/...` to allow for multiple instances of an element on a page. I have the feeling this is what `data-spirit-id` is meant to do but since root isn't saving, it's hard to test! 

(Also, being able to manually edit the XPath so I can select SVG groups rather than shapes/paths would be great too! I've tried editing the JSON, but it gets overwritten when Spirit saves)

**Comment by inlet** [comment]
Hi @Tam,

Thanks for your feedback! 

Yes, I'm aware of this. Will fix it soon!

The reason why I didn't store it initially, is because on the implementation level the root seems redundant:

```javascript
document.querySelectorAll('.ghost').forEach(el => {
  spirit.load('ghost.json', el) // el is the root here for `ghost.json` groups
})
```

But when you're loading multiple groups (like the examples on https://spiritapp.io), it's desirable to have the root in the JSON as well, so different groups are parsed correctly (as you might have the same relative xpaths/ids for each collection of groups).

**Comment by Tam** [comment]
Good to hear!

Is there any performance overhead to loading in the animation JSON for every element that needs animating? Say for example I have an animated icon set with icons being used multiple times in a page. Wouldn't there be a cost to loading the JSON for each unique instance of an icon?

**Comment by inlet** [comment]
**Root element**

I've decided not to store the root path to JSON. It's only needed for element resolving during the [Create Group](https://spiritapp.io/getting-started#CreateGroup) process. 
On implementation-level you'll need to provide the root yourself, so the xpaths/ids of the elements are resolved relative to the provided root: `spirit.load('animation.json', document.querySelector('.root'))`.

Instead I'm going to change the desktop app UI slightly, so it's more clear you can only save/export groups per root.

![image](https://user-images.githubusercontent.com/232559/33128473-d0112a40-cf8c-11e7-9148-71a5995de8c5.png)


**Performance overhead**

You can safely load the same data, the requests are cached at runtime: See [`jsonloader.js`](https://github.com/spirit/spirit/blob/master/src/utils/jsonloader.js#L21)

So calling `spirit.load('./ghost.json')` multiple times results in 1 request. See [`utils-spec.js`](https://github.com/spirit/spirit/blob/master/test/utils-spec.js#L91)

**Comment by Tam** [comment]
That makes sense, thanks! 

Love the app so far. Being able to make animations quickly and easily means I can have a lot more fun working on the details of the sites I build and not worry about running out of budget!

**Comment by inlet** [comment]
Thanks @Tam !
