### ISSUE TITLE
Sooo when spirit is available? Signed up for updates half of a year. No news yet.

### ISSUE THREAD

**Issue by idchlife** [spirit/spirit#2]
How's it going?

**Comment by inlet** [comment]
Hi @idchlife, glad to see you're enthousiast! I'm still working hard on the beta every day. Some minor fixes and it's ready for testing to a select group of people.. I try to collect as much feedback to make the app even better for the first major version.

Making lot's of progress, can't wait to show it to the world! I will definitely keep you posted.

If you have any question (on progress or anything else) feel free to email me. Please let's keep these github issues for code related stuff only ;) thanks man!
