### ISSUE TITLE
Refresh Group when elements in DOM are removed / added

### ISSUE THREAD

**Issue by gurmukhp** [spirit/spirit#20]
**Spirit version:**
2.1.3

- Define animation with data-spirit-id='highlighter-container'.
- Ensure element does not exist on page
- Run spirit.load()
- Add element to page
- Play timeline

**Expected behavior:**
Animation is executed on newly added element.

**Actual behavior:**
First element on page is animated

**Comment by inlet** [comment]
Thanks @gurmukhp will look into it
