### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by bramvdpluijm** [spirit/spirit#24]
I've been trying to use Spirit with React in a server side rendering setup, but haven't managed to get that working. I have no clue why, because Spirit doesn't output any error messages. Could it be GSAP having a hard time on the serverside?

**Comment by inlet** [comment]
Constructing timelines can only be done in the browser (accessing the DOM), calling `spirit.create()`, `spirit.load()` and `spirit.setup()` should throw an exception. 

 I now see I've forgot to implement the check for `spirit.loadAnimation()` though. Will add that.

### Simple solution

Create a React animation component which do a check if it renders in the browser.

Example:

`Animation.js`

```es6
import isNode from 'detect-node'
import spirit from 'spiritjs'

export default class Animation extends React.Component {

  componentDidMount() {
    if (!isNode) {
      const { path, loop, yoyo, autoPlay } = this.props
      spirit.loadAnimation({ container: this._container, loop, yoyo, autoPlay })
    }
  }

  render() {
    return (
      <div ref={c => this._container = c}>
        {this.props.children}
      </div>
    )
  }

}
```

`Component.js`

```es6
import Animation from './Animation'

export default () => (
  <div>
    <Animation path="./animations.json" loop={true} autoPlay={true}>
      <svg>
        ...
      </svg>
    </Animation>
  </div>
)
```

Let me know if you encounter any issues, thanks!

**Comment by inlet** [comment]
I'm closing this issue now, please let me know if you encounter any issues implementing Spirit server side.
