### ISSUE TITLE
Intended browser support

### ISSUE THREAD

**Issue by olsp** [spirit/spirit#26]
I haven't found any information on browser support, but running it in IE11, I get the following error message in console: `'Promise' is undefined`.

The code I'm running is the following:

```
spirit.loadAnimation({
    loop: false,
    delay: 2,
    yoyo: true,
    path: './group.json'
});
```

Spirit version: 2.2.4

**Comment by inlet** [comment]
The web player doesn't include any polyfill by default, this to make the lib as small as possible.
You can safely use https://polyfill.io to ensure `Promise` support.

Docs: https://docs.spiritapp.io/gsap_runtime_browser_support.html

Closing this issue now, please let me know if this solves your problem. Thanks

**Comment by olsp** [comment]
Sorry to get back to this again, but it still doesn't work on IE11. I don't get any errors now, it just doesn't play. In Edge and other browsers it works as intended. 
Should it work in IE11?
