### ISSUE TITLE
Do show warning about development version when it's a normal situation

### ISSUE THREAD

**Issue by Spy-Seth** [spirit/spirit#29]
**Spirit version:**
v2.3

**Expected behavior:**
When I use a dev version of the library in a development environment I should not be warn about the fact I use a development version of the library: this a normal state. 

The library should only warm me if I use a dev version of the library in production

**Actual behavior:**
The library warn me if I use dev version of the library in development. 

See here: https://github.com/spirit/spirit/blob/315de8080051dff1a13abba3ec18a15a24b22907/src/index.js#L41-L43

**Comment by inlet** [comment]
Debug is turned on by default if:

✓ Running in browser
✓ Running the minified build version

https://github.com/spirit/spirit/blob/315de8080051dff1a13abba3ec18a15a24b22907/src/config/config.js#L5

However you can enable/disable debug statements: `spirit.config.debug = false|true`.

> console.warn(`You are running the development build of Spirit v${version}.`)

This warning is only to tell you that you're using the development build. If you're using a module bundler the environment `process.env.NODE_ENV` is used.

**Comment by inlet** [comment]
I'll close this issue as this is the expected behaviour. Please let me know if you think this should be reopened. 

Thanks!
