### ISSUE TITLE
Issues in react environment

### ISSUE THREAD

**Issue by Itzik217** [spirit/spirit#32]
Hello and thanks in advance for taking a look at this.

Ok so, our codebase is made using react and rollup as the transpiler to manage dependencies. I've integrated the way you mentioned, but the issue is that code needs to be added to specific components that then get compiled in order to assign the animation to the desired component. Therefore I added the npm package, and imported the spirit package I've tried to to load the saved animation (Json file) but it was not matched since it's not clear where do the data-spirit-ids should go in order to render it properly. I guess I’m not really sure how to tight up to the html the elements. I wish we can screen share and I can show you the issue. Let me know if this is a possibility.

In addition the npm package has been giving me issues so not sure if it is reliable to integrate?
codebase

**Spirit version:**

**Code to reproduce:**

**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by inlet** [comment]
Hi @Itzik217 

This lib is written in vanilla js and can be used in any framework. I've created a simple codesandbox demo that shows how you can use it in React (this demo uses create-react-app):

https://codesandbox.io/s/spirit-in-react-iqwxl

Important is that the `data-spirit-id` attributes in your SVG matching up with the `id` property in your JSON.

Please let me know if you have solved this issue. If not we can setup a screen share sometime.

Thanks

**Comment by Itzik217** [comment]
Hi Patrick,

Thanks for the response. This is a comment from my integrator.

I do understand how the animation.json is supposed to work, and i do
already have Spirit macOS on my computer and the chrome extension, the
issue is to add CORRECTLY the npm package into our workflow (spirit/spirit
<https://github.com/spirit/spirit> )

It seems to be added, but even by using the chrome extension I get the
following error.
[image: Screen Shot 2019-12-15 at 11.39.03 PM.png]

This happened while loading animation.json or from the chrome extension,
and I can't figure out why, and i’m 100% sure this is because “rollup”, I
will get back to this today or on Monday but it might not get that far, if
the team from SpiritJS can make an example of spiritJS + rollup, that will
be great.

Any idea how to resolve this?

Much appreciated.

Isaac
-- 
Isaac Cohen

http://www.zoomcreative.com

Mobile: +1 (514) 928 9842

United States
Canada
United Kingdom

**Comment by inlet** [comment]
Hi @Itzik217,

This lib exports a `commonjs` version via babel:
https://github.com/spirit/spirit/blob/b2a0877d6b3a82b27a05217e61ddbda2519005f9/package.json#L17

Which should work in all bundlers (that have babel support), I haven't tested it in Rollup though. It works in Webpack and Parcel (used in other projects).

I think this issue is related to your rollup config and how modules are loaded. 

A possible workaround:

- Include the [browser version](https://unpkg.com/spiritjs/dist/spirit.js) in your html before you load your main app
- Use `window.spirit` where you'd like to play spirit animations.

Example:

`html`:

```html
<script src="https://unpkg.com/spiritjs/dist/spirit.js"></script>
<script src="./your-app.js"></script>
```

`Animation.js`:

```jsx
import React from "react";

const Animation = ({ children, data, loop }) => {
  const containerRef = React.useRef();

  React.useEffect(() => {
    const container = containerRef.current;

    // 👇
    window.spirit.loadAnimation({ path: data, loop, container });
      
    return () => window.spirit.groups.clear();
  }, [data, loop]);

  return (
    <div className="spirit-container" ref={containerRef}>
      {children}
    </div>
  );
};

export default Animation;
```

**Comment by Itzik217** [comment]
Thanks Patrick.

None related, Is there a way to control the animation on a user action (ie
on mouseover, touch, click etc) in studio. Please get back to me when you
can.

Thanks!
Isaac
-- 
Isaac Cohen

http://www.zoomcreative.com

Mobile: +1 (514) 928 9842

United States
Canada
United Kingdom

**Comment by inlet** [comment]
With Spirit Studio you can create/edit the animations. It exports the animation JSON which the web player can read and play the animations on the web.

The web player exports GSAP animations, which you can control in any possible way.

Resources:

https://docs.spiritapp.io/web-player/extended-api/interactive.html#example
https://docs.spiritapp.io/web-player/simple-api.html#adding-interactivity

Examples:

https://codepen.io/inlet/pen/748b83ac7a600c2a67b6dea365d43dd1
https://codepen.io/inlet/pen/c9e6a1f6a7e786e33ff1ad2ad5151f15
https://codepen.io/inlet/pen/415e03ac6cea9c8090020293f800ba70
https://codepen.io/inlet/pen/7fb7f5657e6d7f5758044ee679c0ceb8
https://codepen.io/inlet/pen/600f2046cc0afbf33a42b3926a9ea71d

This video tut helps as well:

https://www.youtube.com/watch?v=pggg-W3qS_o

Feel free to email support if you have any additional questions.
