### ISSUE TITLE
I'm having a lot of trouble getting Spirit to work with Next.js.

### ISSUE THREAD

**Issue by botelhos** [spirit/spirit#35]
Spirit version: 1.1.3

Code to reproduce: `spirit.loadAnimation({ path: './my-animation.json' })`

Expected behavior: Animation

Actual behavior: Nothing

Additional information: I'm having a lot of trouble getting Spirit to work with Next.js, you know how I can embed my animations from a component?

**Comment by inlet** [comment]
Hi @botelhos, 

Can you share what you're seeing in the console? Any JS errors?
I'm not familiar with your codebase, but normally you can easily load the animation on mounting a React component, for instance:

```jsx
const MyAnimation = ({ path }) => {
  React.useEffect(() => {
    spirit.loadAnimation({ path }).then(timeline => {
      console.log('timeline: ', timeline);
    });
  }, [path]);

  return (...)
}
```

**Comment by inlet** [comment]
Btw, best is to avoid collisions and assign the animation to a root container.

Example:

```jsx
const MyAnimation = ({ path }) => {
  const containerRef = React.useRef();

  React.useEffect(() => {
    spirit.loadAnimation({ 
      path, 
      container: containerRef.current 
    });
  }, [path]);

  return (
    <div ref={containerRef}>
      <svg>
        <path d="..." data-spirit-id="my-path-1" />
        <path d="..." data-spirit-id="my-path-2" />
      </svg>
    </div>
  );
}
```

Now `my-path-1` and `my-path-2` are resolved based on its container.
